service: serverless-node-text-message-app

plugins:
  - serverless-dotenv-plugin
  - serverless-finch

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    # Replace these environment variables with your Twilio and Google values
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
    GOOGLE_RECAPTCHA_TOKEN: ${env:GOOGLE_RECAPTCHA_TOKEN}

functions:
  validateRecaptchaSendSms:
    handler: dist/handler.validateAndSend
    events:
      - http:
          path: api/sendSms
          method: post
          integration: lambda
          cors: true

custom:
  client:
    bucketName: ${env:BUCKET_NAME}